# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias gl='git log --topo-order --branches --remotes --tags --graph --pretty=format:"${_git_log_oneline_format}"'
alias gl='git log --branches --remotes --tags --graph --oneline --decorate'
alias gs='git status'
alias gd='git diff'
alias bi='bundle install'
alias be='bundle exec'
alias pi='pod install'
alias gaa='git add -A'
alias sourcetree='open -a SourceTree'
alias fbt='sudo killall coreaudiod'
alias gsync='git pull --rebase && git push'
alias gss='git add -A && git stash'
alias reload='. ~/.zshrc'
alias vscode='code'
alias kc='kubectl'
alias kx='kubectx'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Golang
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# Python
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Init rbenv
#eval "$(rbenv init -)"

# Init pyenv
#eval "$(pyenv init -)"

# Swap filename
function swap()
{
    local TMPFILE=tmp.$$
    mv "$1" $TMPFILE
    mv "$2" "$1"
    mv $TMPFILE "$2"
}

# Android
# export PATH=$PATH:$HOME/Library/Android/sdk/tools

# CUDA lib
export LD_LIBRARY_PATH=/usr/local/cuda/lib64/

# NodeJS
export PATH=~/.npm-global/bin:$PATH

# added by Miniconda3 installer
export PATH="$HOME/miniconda3/bin:$PATH"
export PATH="/opt/miniconda3/bin:$PATH"

export TERM=xterm-256color
export VISUAL=vim

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
