# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias gl='git log --topo-order --branches --remotes --tags --graph --pretty=format:"${_git_log_oneline_format}"'
alias gl='git log --branches --remotes --tags --graph --oneline --decorate'
alias gs='git status'
alias gd='git diff'
alias bi='bundle install'
alias be='bundle exec'
alias pi='pod install'
alias gaa='git add -A'
alias sourcetree='open -a SourceTree'
alias fbt='sudo killall coreaudiod'
alias gsync='git pull --rebase && git push'
alias gss='git add -A && git stash'
alias reload='. ~/.zshrc'
alias vscode='code'
alias kc='kubectl'
alias kx='kubectx'
alias kn='kubens'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# FZF initialization
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh
[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh

# Golang
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# Python
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Init rbenv
export PATH=$HOME/.rbenv/bin:$PATH
[ -x "$(command -v rbenv)" ] && eval "$(rbenv init -)"

# Init pyenv
[ -x "$(command -v pyenv)" ] && eval "$(pyenv init -)"

# Init nvm
#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Android
# export PATH=$PATH:$HOME/Library/Android/sdk/tools

# CUDA lib
export LD_LIBRARY_PATH=/usr/local/cuda/lib64/

# NodeJS
export PATH=~/.npm-global/bin:$PATH

# Correct color profile
export TERM=xterm-256color

# Set default editor
export VISUAL=vim
export EDITOR=vim

# Setup conda
#export PATH="/Users/jeep/miniconda3/bin:$PATH"

# Gitignore utility
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

# Fix VTE issue
if [[ $TILIX_ID ]]; then
        source /etc/profile.d/vte.sh
fi

# >>> conda initialize >>>
export PATH="$HOME/miniconda3/bin:$PATH"
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/jeep/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/jeep/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/jeep/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/jeep/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jeep/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jeep/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jeep/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jeep/google-cloud-sdk/completion.zsh.inc'; fi

# Autocompletion for helm
source <(helm completion zsh)

# Autocompletion for kubectl
source <(kubectl completion zsh)

